### ISSUE TITLE
Test the AI

### ISSUE THREAD

**Issue by Aerylia** [dljve/wordwar#1]
I have created the AI, but it still needs to be tested whether it works

The AI is run by running the server.
Two AIs are created, one creates a game, the other joins it.
Then, the server waits for a third player to join the game and gives a starting sign to the two AIs to start playing.
It should have a similar behaviour to that of a human in terms of response times and forgetting words according to slim stampen.

**Comment by dljve** [comment]
The server outputs:

```
8888
Server listening...
Server: NEW CONNECTION Socket[addr=/127.0.0.1,port=55822,localport=8888]
Handling serverSide: com.applab.wordwar.server.handlers.InitHandler@1501d40
Server: NEW CONNECTION Socket[addr=/127.0.0.1,port=55823,localport=8888]
Handling serverSide: com.applab.wordwar.server.handlers.InitHandler@39a314bc
Handling serverSide: com.applab.wordwar.server.handlers.CreateGameHandler@2835216
0
java.io.StreamCorruptedException: invalid type code: AC
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1381)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at com.applab.wordwar.server.TempRivialClient.run(TempRivialClient.java:191)
	at java.lang.Thread.run(Thread.java:745)
java.io.StreamCorruptedException: invalid stream header: ED000573
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:808)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:301)
	at com.applab.wordwar.server.TempRivialClient.run(TempRivialClient.java:188)
	at java.lang.Thread.run(Thread.java:745)
java.io.StreamCorruptedException: invalid stream header: 72003463
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:808)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:301)
	at com.applab.wordwar.server.TempRivialClient.run(TempRivialClient.java:188)
	at java.lang.Thread.run(Thread.java:745)
```
